# pull official base image
FROM python:3.8

# set work directory
WORKDIR /usr/src/backend

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV DEBUG 1
RUN apt-get update &&  apt-get upgrade -y &&  pip install --upgrade pip
RUN apt-get install -y  netcat-openbsd libpq-dev build-essential 
# install system dependencies


COPY ./requirements.txt .
RUN pip install -r requirements.txt

# copy entrypoint.sh
COPY ./entrypoint.sh .
RUN sed -i 's/\r$//g' /usr/src/backend/entrypoint.sh && chmod +x /usr/src/backend/entrypoint.sh


# copy project
COPY . .

# run entrypoint.sh
ENTRYPOINT ["/usr/src/backend/entrypoint.sh"]