version: "3.9"

services:
  web:
    build: ../backend
    command: python3 manage.py runserver 0.0.0.0:8009
    volumes:
      - ./transcendence/:/usr/src/transcendence/
    ports:
      - 8009:8009
    env_file:
      - ../.env.dev
    depends_on:
      - db

  nginx:
    build: ../nginx
    ports:
      - "3000:3000" # Map port 80 of the container to port 80 of the host
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro # Mount the configuration file as read-only

  db:
    image: postgres:16.2
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev

volumes:
  postgres_data:
